{% set name = "jfrog-cli" %}
{% set version = "2.78.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jfrog/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 23f1fd98af8331818729d0255d0334b479f7681bd8577b0023813787740d7f5f

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - {{ compiler("go-nocgo") }}
    - go-licenses

test:
  commands:
    - jf --help

about:
  home: https://jfrog.com/getcli/
  dev_url: https://github.com/jfrog/jfrog-cli
  summary: JFrog CLI is a client that provides a simple interface that automates access to the JFrog products.
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/

extra:
  recipe-maintainers:
    - moritzwilksch
