{% set name = "jfrog-cli" %}
{% set version = "2.78.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jfrog/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8e65ea2ddfb7d33c63e977836b21228d85a9b01105c5d07e8efab6529a8c8fa6

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - {{ compiler("go-nocgo") }}
    - go-licenses

test:
  commands:
    - jf --help

about:
  home: https://jfrog.com/getcli/
  dev_url: https://github.com/jfrog/jfrog-cli
  summary: JFrog CLI is a client that provides a simple interface that automates access to the JFrog products.
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/

extra:
  recipe-maintainers:
    - moritzwilksch
