{% set name = "jfrog-cli" %}
{% set version = "2.78.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jfrog/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c16c0abbbfc5e477ce898d5e40dcb756f5a75793d02b03ee32a632844a9e2016

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - {{ compiler("go-nocgo") }}
    - go-licenses

test:
  commands:
    - jf --help

about:
  home: https://jfrog.com/getcli/
  dev_url: https://github.com/jfrog/jfrog-cli
  summary: JFrog CLI is a client that provides a simple interface that automates access to the JFrog products.
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/

extra:
  recipe-maintainers:
    - moritzwilksch
