{% set name = "jfrog-cli" %}
{% set version = "2.70.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jfrog/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0bb7e009a9148026cc5e3acd93a692d72841da42fdd301e0892a9f6e1d949db9

build:
  number: 1
  binary_relocation: false

requirements:
  build:
    - {{ compiler("go-nocgo") }}
    - go-licenses

test:
  commands:
    - jf --help

about:
  home: https://jfrog.com/getcli/
  dev_url: https://github.com/jfrog/jfrog-cli
  summary: JFrog CLI is a client that provides a simple interface that automates access to the JFrog products.
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/

extra:
  recipe-maintainers:
    - moritzwilksch
